### ISSUE TITLE
installation failures on Mac OS/Anaconda and Windows 10/Anaconda

### ISSUE THREAD

**Issue by thaynecurrie** [jlparkI/outlier_robust_polyfit#1]
Hi: 

I have installation failures for this package with Anaconda-Python3 on MacOS and Windows 10.  The error states:
"
    ValueError: 'src/RobustPolyfit/RobustPolyfit.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output."

The commands used to install were
pip install robustpolyfit and pip3 install robustpolyfit

**Comment by jlparkI** [comment]
I have repackaged this as a source distribution. You should still be able to install using:

pip install RobustPolyfit==0.0.8

It contains a C extension which will compile automatically. If on Windows you get an error "Microsoft Visual C++ 14.0 is required", this can be fixed as described here:

https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required

On Linux this should be very straightforward.
